version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./.env:/app/.env
